import type { Exercise } from "./types";

/**
 * Bibliothèque d'exercices.
 * Répartition : 18 core, 8 padel, 8 volley-ball (34 au total).
 * Chaque exercice : étapes concrètes, phrases utilisables mot pour mot,
 * variante express (≤ 20 s) quand c'est pertinent.
 */
export const EXERCICES: Exercise[] = [
  // ————————————————————————— CORE —————————————————————————
  {
    id: "respiration-4-6",
    titre: "Respiration 4-6",
    categorie: "respiration",
    duree: 3,
    difficulte: "facile",
    quand: ["avant", "pendant", "hors-terrain"],
    objectif: "Faire redescendre la tension en allongeant l'expiration.",
    description: "Inspire sur 4 temps, expire sur 6. L'expiration longue envoie au corps un signal de calme.",
    etapes: [
      "Assieds-toi ou reste debout, pieds bien posés.",
      "Inspire par le nez en comptant jusqu'à 4.",
      "Si c'est confortable, garde l'air 2 secondes. Sinon, passe directement à l'expiration.",
      "Expire par la bouche en comptant jusqu'à 6, comme dans une paille.",
      "Répète 6 cycles. Si tu as la tête qui tourne, reprends une respiration normale.",
    ],
    express: { texte: "Une seule inspiration sur 4, une expiration sur 6. Épaules basses.", secondes: 10 },
    guide: { type: "respiration", inspire: 4, pause: 2, expire: 6, cycles: 6 },
    sports: ["all"],
    principe: "respiration",
  },
  {
    id: "double-inspiration",
    titre: "Le soupir qui relâche",
    categorie: "respiration",
    duree: 1,
    difficulte: "facile",
    quand: ["pendant", "avant"],
    objectif: "Relâcher rapidement la tension quand tu sens le cœur accélérer.",
    description: "Deux petites inspirations par le nez, puis une longue expiration par la bouche. Rapide et discret.",
    etapes: [
      "Inspire par le nez.",
      "Ajoute une deuxième petite inspiration par-dessus, pour remplir le haut des poumons.",
      "Expire lentement par la bouche, jusqu'au bout.",
      "Répète deux ou trois fois.",
      "Si tu as la tête qui tourne, reprends une respiration normale.",
    ],
    express: { texte: "Deux inspirations par le nez, une longue expiration. Une fois.", secondes: 8 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "respiration",
  },
  {
    id: "respiration-tonique",
    titre: "Respiration tonique",
    categorie: "respiration",
    duree: 1,
    difficulte: "facile",
    quand: ["avant", "pendant"],
    objectif: "Remonter ton énergie quand tu te sens lourd ou endormi.",
    description: "Des inspirations dynamiques et un corps qui bouge, pour réveiller le système.",
    etapes: [
      "Debout, redresse-toi, poitrine ouverte.",
      "Inspire vite par le nez en levant les bras.",
      "Souffle fort par la bouche en les redescendant.",
      "Fais-le 3 fois, puis deux petits sauts sur place.",
      "Dis-toi : « Réveillé. Prêt. »",
    ],
    express: { texte: "Trois respirations rapides et deux petits sauts.", secondes: 12 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "activation",
  },
  {
    id: "reset-3r",
    titre: "Reset en 3 temps",
    categorie: "erreurs",
    duree: 3,
    difficulte: "facile",
    quand: ["pendant", "hors-terrain"],
    objectif: "Transformer une erreur en information, puis repartir.",
    description: "Reconnaître, Relâcher, Recentrer. Une séquence courte qui devient automatique à force de répétition.",
    etapes: [
      "Reconnaître : dis le fait, sans jugement. « Trop long. »",
      "Relâcher : une longue expiration et un geste de clôture (main qui s'ouvre, cordage essuyé…).",
      "Recentrer : choisis une intention pour l'action suivante. « Plus de hauteur. »",
      "Entraîne-toi : repense à 3 erreurs récentes et fais la séquence pour chacune.",
    ],
    express: { texte: "Le fait. Une expiration. Une intention.", secondes: 10 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "erreur-information",
  },
  {
    id: "carnet-erreurs",
    titre: "Mes erreurs, mes infos",
    categorie: "erreurs",
    duree: 7,
    difficulte: "moyen",
    quand: ["apres", "hors-terrain"],
    objectif: "Apprendre de tes erreurs sans les ruminer.",
    description: "Tu notes une erreur comme une donnée, puis tu en tires une seule consigne pour la prochaine fois.",
    etapes: [
      "Choisis une erreur qui revient souvent.",
      "Décris-la en une phrase factuelle : quoi, quand, dans quelle situation.",
      "Écris ce que ton corps ou ta tête faisait juste avant.",
      "Écris une consigne positive pour la prochaine fois : « Je fléchis plus tôt. »",
      "Choisis un mot pour la résumer. Tu l'utiliseras en match.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "erreur-information",
  },
  {
    id: "geste-cloture",
    titre: "Mon geste de clôture",
    categorie: "erreurs",
    duree: 5,
    difficulte: "facile",
    quand: ["hors-terrain", "pendant"],
    objectif: "Créer un geste qui ferme physiquement le point précédent.",
    description: "Un geste répété souvent devient un signal : « c'est fini, au suivant ».",
    etapes: [
      "Choisis un geste simple : essuyer ton cordage, frotter tes paumes, serrer puis ouvrir la main.",
      "Associe-le à une expiration longue.",
      "Ajoute un mot : « Suivant. »",
      "Répète-le 10 fois à la maison, en pensant à une erreur à chaque fois.",
      "À l'entraînement, fais-le après chaque erreur, sans exception.",
    ],
    express: { texte: "Ton geste, une expiration, « Suivant ».", secondes: 5 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "erreur-information",
  },
  {
    id: "ancrage-balle",
    titre: "Ancrage sur la balle",
    categorie: "concentration",
    duree: 5,
    difficulte: "facile",
    quand: ["hors-terrain", "avant"],
    objectif: "Entraîner ton attention étroite sur un détail précis.",
    description: "Tu observes une balle comme si tu la découvrais. Ton attention apprend à se poser et à y revenir.",
    etapes: [
      "Prends une balle ou un ballon dans tes mains.",
      "Observe pendant une minute : couleur, coutures, logo, texture.",
      "Quand ton esprit part ailleurs, remarque-le et reviens à un détail de la balle.",
      "Ferme les yeux et sens son poids, sa forme, sa température.",
      "Rouvre les yeux et nomme trois détails que tu n'avais pas vus.",
    ],
    express: { texte: "Fixe un détail de la balle pendant une expiration.", secondes: 6 },
    guide: { type: "minuteur", secondes: 180 },
    sports: ["all"],
    principe: "attention",
  },
  {
    id: "large-etroit",
    titre: "Zoom large, zoom serré",
    categorie: "concentration",
    duree: 5,
    difficulte: "moyen",
    quand: ["hors-terrain", "avant"],
    objectif: "Apprendre à basculer entre lire le jeu et fixer la balle.",
    description: "Comme un appareil photo : grand angle pour lire, zoom pour exécuter.",
    etapes: [
      "Regarde la pièce en entier, sans fixer : tu perçois tout le champ. C'est l'attention large.",
      "Choisis maintenant un objet précis et fixe-le. C'est l'attention étroite.",
      "Alterne toutes les 10 secondes : « Large… Serré… »",
      "Sur le terrain, l'attention large sert entre les échanges, l'étroite au moment de frapper.",
      "Dis-toi en match : « Large » quand tu te replaces, « Balle » quand elle arrive.",
    ],
    express: { texte: "« Large » en te replaçant, « Balle » au moment de jouer.", secondes: 5 },
    guide: { type: "minuteur", secondes: 240 },
    sports: ["all"],
    principe: "attention",
  },
  {
    id: "mot-cle",
    titre: "Choisir mon mot-clé",
    categorie: "concentration",
    duree: 5,
    difficulte: "facile",
    quand: ["hors-terrain"],
    objectif: "Avoir un mot court qui te ramène dans le présent.",
    description: "Un mot d'une ou deux syllabes, associé à une sensation, que tu retrouveras en plein match.",
    etapes: [
      "Rappelle-toi un moment où tu jouais bien, l'esprit clair.",
      "Quel mot décrit cette sensation ? « Fluide », « Ici », « Simple », « Souffle »…",
      "Dis-le à voix basse en expirant. Sens ce qu'il évoque.",
      "Enregistre-le dans ton profil.",
      "Utilise-le à l'entraînement avant chaque point pendant une semaine.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "autodialogue",
  },
  {
    id: "carnet-preuves",
    titre: "Mon carnet de preuves",
    categorie: "confiance",
    duree: 7,
    difficulte: "facile",
    quand: ["hors-terrain", "apres"],
    objectif: "Construire ta confiance sur des faits réels.",
    description: "La confiance tient mieux sur des preuves que sur des promesses. Tu les collectes, une par une.",
    etapes: [
      "Note 3 moments où tu as bien joué ou bien réagi. Sois précis : quand, quoi, comment.",
      "Note 2 choses que tu as faites pour te préparer (entraînements, efforts, progrès).",
      "Relis-les à voix basse.",
      "Avant un match, relis ta preuve préférée.",
      "Ajoute une nouvelle preuve après chaque match.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "confiance-preuves",
  },
  {
    id: "coequipier-interieur",
    titre: "Me parler comme à un coéquipier",
    categorie: "confiance",
    duree: 5,
    difficulte: "moyen",
    quand: ["hors-terrain", "pendant"],
    objectif: "Remplacer l'autocritique par un dialogue utile et bienveillant.",
    description: "Tu te parles comme tu parlerais à un coéquipier que tu apprécies, à la deuxième personne.",
    etapes: [
      "Rappelle-toi une phrase dure que tu te dis souvent après une erreur.",
      "Imagine qu'un coéquipier fait la même erreur. Que lui dirais-tu ?",
      "Reformule pour toi, en disant « tu » : « Tu respires, tu joues ton point. »",
      "Ajoute une consigne concrète : « Jambes. Regarde la balle. »",
      "Écris ta phrase et garde-la pour le match.",
    ],
    express: { texte: "« Tu respires. Tu joues ton point. »", secondes: 4 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "autodialogue",
  },
  {
    id: "posture-energie",
    titre: "Posture de joueur prêt",
    categorie: "confiance",
    duree: 2,
    difficulte: "facile",
    quand: ["avant", "pendant"],
    objectif: "Utiliser ton corps pour soutenir ton état d'esprit.",
    description: "Une posture ouverte et des appuis vivants t'aident à rester engagé entre les points.",
    etapes: [
      "Pieds largeur d'épaules, genoux souples.",
      "Redresse le dos, ouvre la poitrine, regard à l'horizon.",
      "Relâche les épaules et la mâchoire.",
      "Fais quelques petits pas sur place : appuis vivants.",
      "Garde cette posture en marchant vers ta position.",
    ],
    express: { texte: "Regard haut, épaules basses, petits pas.", secondes: 5 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "confiance-preuves",
  },
  {
    id: "si-alors",
    titre: "Mes plans « si… alors… »",
    categorie: "pression",
    duree: 7,
    difficulte: "moyen",
    quand: ["hors-terrain", "avant"],
    objectif: "Préparer tes réponses aux moments difficiles avant qu'ils arrivent.",
    description: "Un plan simple décidé à froid est bien plus facile à appliquer à chaud.",
    etapes: [
      "Liste 3 situations qui te mettent sous pression (ex. balle de set, série adverse, erreur bête).",
      "Pour chacune, écris : « Si [situation], alors je [action concrète]. »",
      "Exemple : « Si je rate une balle facile, alors j'expire longuement et je choisis mon prochain coup. »",
      "Lis tes plans à voix haute deux fois.",
      "Relis-les avant ton prochain match.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "process",
  },
  {
    id: "activation-utile",
    titre: "Mon niveau d'activation",
    categorie: "pression",
    duree: 5,
    difficulte: "moyen",
    quand: ["hors-terrain", "avant"],
    objectif: "Trouver ton niveau d'énergie idéal, ni trop bas, ni trop haut.",
    description: "La pression, c'est de l'énergie. L'objectif : un niveau utile, pas le calme absolu.",
    etapes: [
      "Sur une échelle de 1 à 5, à quel niveau d'énergie as-tu joué ton meilleur match ?",
      "Que ressentais-tu dans le corps ? (cœur, mains, jambes, respiration)",
      "Note une action pour monter d'un cran (sautiller, respirer vite, se redresser).",
      "Note une action pour descendre d'un cran (expiration longue, relâcher les épaules).",
      "Avant chaque match, évalue ton niveau et ajuste.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "activation",
  },
  {
    id: "simulation-pression",
    titre: "Simuler la pression",
    categorie: "pression",
    duree: 10,
    difficulte: "avance",
    quand: ["hors-terrain"],
    objectif: "T'habituer aux moments clés à l'entraînement.",
    description: "Tu crées des enjeux artificiels à l'entraînement pour répéter ta routine sous tension.",
    etapes: [
      "Choisis un exercice d'entraînement simple.",
      "Ajoute un enjeu : « 3 réussites d'affilée, sinon on recommence à zéro ».",
      "Avant chaque tentative, fais ta routine : relâche, lis, décide, engage.",
      "Remarque ce que fait ton corps quand l'enjeu monte. C'est normal : utilise cette énergie.",
      "Après la séance, note ce qui t'a aidé à rester dans ta routine.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "activation",
  },
  {
    id: "visualisation-coping",
    titre: "Visualisation : erreur puis rebond",
    categorie: "avant-match",
    duree: 3,
    difficulte: "moyen",
    quand: ["avant", "hors-terrain"],
    objectif: "Préparer ton cerveau à bien réagir après une erreur.",
    description: "Tu imagines une séquence réaliste, avec une erreur et une récupération réussie, à vitesse réelle.",
    etapes: [
      "Ferme les yeux. Vois le terrain depuis tes propres yeux.",
      "Ajoute les sons et les sensations : la balle, tes appuis, ta respiration.",
      "Joue un point à vitesse réelle, en entier.",
      "Imagine une erreur. Vois-toi faire ton geste de clôture et expirer longuement.",
      "Joue le point suivant avec engagement, et vois-le réussir.",
      "Répète la séquence deux fois, puis ouvre les yeux.",
    ],
    guide: { type: "minuteur", secondes: 180 },
    sports: ["all"],
    principe: "visualisation",
  },
  {
    id: "intention-du-jour",
    titre: "Mon intention du jour",
    categorie: "avant-match",
    duree: 2,
    difficulte: "facile",
    quand: ["avant"],
    objectif: "Partir au match avec une seule priorité de process.",
    description: "Une intention simple et contrôlable, que tu peux vérifier pendant le match.",
    etapes: [
      "Choisis une seule chose que tu contrôles : ton souffle, ta routine, ton engagement, ta communication.",
      "Formule-la en positif : « Je respire entre chaque point. »",
      "Dis-la à voix basse trois fois.",
      "Associe-la à ton mot-clé.",
    ],
    express: { texte: "Rappelle-toi ton intention et dis ton mot-clé.", secondes: 5 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "process",
  },
  {
    id: "bilan-3-questions",
    titre: "Bilan en 3 questions",
    categorie: "apres-match",
    duree: 5,
    difficulte: "facile",
    quand: ["apres"],
    objectif: "Apprendre de ton match en restant centré sur le process.",
    description: "Trois questions pour garder ce qui marche et choisir une piste, quel que soit le score.",
    etapes: [
      "Qu'est-ce qui a bien marché aujourd'hui ? Note au moins une chose précise.",
      "À quel moment as-tu bien rebondi ? Qu'as-tu fait à ce moment-là ?",
      "Quelle est ta seule piste de travail pour la prochaine fois ?",
      "Ajoute ta réussite à ton carnet de preuves.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "process",
  },
  {
    id: "relachement-apres-match",
    titre: "Décompresser après le match",
    categorie: "apres-match",
    duree: 4,
    difficulte: "facile",
    quand: ["apres"],
    objectif: "Faire redescendre la tension et tourner la page.",
    description: "Un retour au calme du corps et de la tête, avant de passer à autre chose.",
    etapes: [
      "Assieds-toi. Expire longuement 5 fois.",
      "Contracte les épaules 5 secondes, puis relâche. Même chose avec les mains, puis les jambes.",
      "Pense à un moment du match dont tu peux être content.",
      "Dis-toi : « Le match est fini. Je garde la leçon, je laisse le reste. »",
    ],
    guide: { type: "minuteur", secondes: 240 },
    sports: ["all"],
    principe: "respiration",
  },
  {
    id: "pourquoi-je-joue",
    titre: "Pourquoi je joue",
    categorie: "motivation",
    duree: 5,
    difficulte: "facile",
    quand: ["hors-terrain"],
    objectif: "Te reconnecter à ce qui te fait aimer ton sport.",
    description: "Le plaisir et le sens nourrissent l'engagement sur la durée.",
    etapes: [
      "Note 3 choses que tu aimes dans ton sport (une sensation, un coup, des personnes…).",
      "Rappelle-toi ton meilleur souvenir de jeu. Où étais-tu ? Avec qui ?",
      "Écris une phrase : « Je joue pour… »",
      "Relis-la avant ta prochaine séance.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "process",
  },
  {
    id: "objectif-process",
    titre: "Un objectif que je contrôle",
    categorie: "motivation",
    duree: 5,
    difficulte: "moyen",
    quand: ["hors-terrain"],
    objectif: "Transformer une envie de résultat en objectif d'action.",
    description: "« Gagner » dépend aussi des autres. « Monter au filet après chaque lob », ça dépend de toi.",
    etapes: [
      "Écris le résultat que tu aimerais obtenir.",
      "Demande-toi : qu'est-ce qui m'en rapprocherait, et que je contrôle entièrement ?",
      "Choisis une action précise et mesurable pour la semaine.",
      "Note-la ici et coche-la à chaque séance où tu l'as faite.",
    ],
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "process",
  },

  {
    id: "phrases-soutien",
    titre: "Mes phrases de soutien",
    categorie: "communication",
    duree: 5,
    difficulte: "facile",
    quand: ["hors-terrain", "pendant"],
    objectif: "Avoir des mots prêts pour soutenir un partenaire ou des coéquipiers.",
    description: "Sous tension, on trouve mal ses mots. Tu les prépares à froid : courts, positifs, utiles.",
    etapes: [
      "Écris une phrase pour après une erreur d'un partenaire : « Suivant, avec toi. »",
      "Écris une phrase pour un moment clé : « Point par point, ensemble. »",
      "Écris une phrase pour une belle action : nomme ce qui était bien.",
      "Avant le match, convenez ensemble : « Que fait-on quand l'un de nous est en difficulté ? »",
      "Utilise au moins une de tes phrases à chaque match.",
    ],
    express: { texte: "Un regard et « Suivant, avec toi. »", secondes: 3 },
    guide: { type: "etapes" },
    sports: ["all"],
    principe: "communication",
  },

  // ————————————————————————— PADEL —————————————————————————
  {
    id: "padel-routine-20s",
    titre: "Routine des 20 secondes",
    categorie: "concentration",
    duree: 5,
    difficulte: "moyen",
    quand: ["pendant", "hors-terrain"],
    objectif: "Utiliser les 20 secondes entre deux points pour te remettre à zéro.",
    description: "Les 4 temps de la routine, calés sur le rythme du padel.",
    etapes: [
      "Relâcher (5 s) : longue expiration, regard sur ton cordage.",
      "Lire (3 s) : un mot sur le point passé. « Court », « Ok », « Trop tôt ».",
      "Décider (5 s) : une intention. « Lob profond », « Volée au centre ».",
      "Engager (5 s) : tape de raquettes, ton mot-clé, regard sur les adversaires.",
      "À l'entraînement, fais-la entre chaque point pendant un set entier.",
    ],
    express: { texte: "Cordage. Un mot. Une intention. Tape de raquettes.", secondes: 20 },
    guide: { type: "minuteur", secondes: 20 },
    sports: ["padel"],
    principe: "routine-4-temps",
  },
  {
    id: "padel-tape-raquettes",
    titre: "Le rituel de la tape de raquettes",
    categorie: "communication",
    duree: 5,
    difficulte: "facile",
    quand: ["avant", "pendant"],
    objectif: "Rester soudés à deux, surtout après un point perdu.",
    description: "Un rituel court et positif entre partenaires, à chaque point, gagné ou perdu.",
    etapes: [
      "Avant le match, convenez d'un rituel : tape de raquettes et un mot.",
      "Choisissez vos mots : « À nous », « Suivant », « Ensemble ».",
      "Après chaque point, gagné ou perdu, faites-le.",
      "Après un point perdu, ajoutez l'intention pour le prochain : « Lob au centre. »",
    ],
    express: { texte: "Tape de raquettes : « À nous. »", secondes: 3 },
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "communication",
  },
  {
    id: "padel-pacte-duo",
    titre: "Le pacte du duo",
    categorie: "communication",
    duree: 8,
    difficulte: "moyen",
    quand: ["avant", "hors-terrain"],
    objectif: "Décider avant le match comment vous vous soutenez dans les moments difficiles.",
    description: "Une conversation de quelques minutes qui évite les tensions en plein match.",
    etapes: [
      "Posez-vous la question : « Que fait-on quand l'un de nous est en difficulté ? »",
      "Chacun dit ce qui l'aide : un mot, un geste, de l'espace, une consigne.",
      "Choisissez une phrase de soutien commune : « On joue ensemble, point par point. »",
      "Mettez-vous d'accord sur les appels : « À toi », « Moi », « Laisse ».",
      "Décidez qui annonce la tactique entre les points.",
    ],
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "communication",
  },
  {
    id: "padel-vitre-patience",
    titre: "La vitre est ton alliée",
    categorie: "pression",
    duree: 5,
    difficulte: "moyen",
    quand: ["hors-terrain", "pendant"],
    objectif: "Gagner en calme sur les balles qui rebondissent sur la vitre.",
    description: "Le rebond sur la vitre te donne du temps. Tu apprends à l'attendre au lieu de te précipiter.",
    etapes: [
      "À l'entraînement, demande des balles qui rebondissent sur la vitre du fond.",
      "Expire pendant que la balle va vers la vitre.",
      "Dis-toi « Attends » pendant le rebond, puis « Frappe » quand elle redescend.",
      "Vise d'abord une sortie haute et sûre : un lob profond.",
      "Fais-en 20, puis demande des balles plus rapides.",
    ],
    express: { texte: "Expire vers la vitre. « Attends… Frappe. »", secondes: 4 },
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "attention",
  },
  {
    id: "padel-break-routine",
    titre: "Ma routine de balle de break",
    categorie: "pression",
    duree: 6,
    difficulte: "avance",
    quand: ["hors-terrain", "pendant"],
    objectif: "Avoir un plan prêt pour les balles de break, pour et contre toi.",
    description: "Tu prépares à l'avance ce que tu fais sur ces points clés, pour jouer comme d'habitude.",
    etapes: [
      "Écris ton plan au service sur balle de break contre toi : « Premier service dans le corps, puis filet. »",
      "Écris ton plan au retour sur balle de break pour toi : « Retour bas au centre, puis lob. »",
      "Ajoute la phrase pour ton partenaire : « Première balle, et on joue. »",
      "À l'entraînement, jouez des jeux qui commencent à 30-40 pour répéter ces plans.",
    ],
    express: { texte: "Expire. Première balle dans le plan. Tape de raquettes.", secondes: 15 },
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "process",
  },
  {
    id: "padel-confiance-lob",
    titre: "Mes coups de confiance",
    categorie: "confiance",
    duree: 6,
    difficulte: "facile",
    quand: ["hors-terrain", "avant"],
    objectif: "Identifier les coups sur lesquels tu peux t'appuyer quand ça se tend.",
    description: "Sous pression, on revient à ses coups sûrs. Encore faut-il savoir lesquels.",
    etapes: [
      "Liste tes 3 coups les plus fiables (ex. lob croisé, volée de revers, bandeja).",
      "Pour chacun, rappelle-toi un point précis où il a fonctionné.",
      "Note-les dans ton carnet de preuves.",
      "En match, sur un point important, choisis l'un d'eux.",
    ],
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "confiance-preuves",
  },
  {
    id: "padel-changement-cote",
    titre: "Le changement de côté",
    categorie: "avant-match",
    duree: 2,
    difficulte: "facile",
    quand: ["pendant"],
    objectif: "Profiter des 90 secondes du changement de côté pour te recentrer.",
    description: "Une mini-routine en trois temps : récupérer, faire le point à deux, repartir.",
    etapes: [
      "Bois, essuie-toi, expire longuement trois fois.",
      "Avec ton partenaire : une chose qui marche, une chose à ajuster.",
      "Choisissez ensemble une intention pour les deux prochains jeux.",
      "Tape de raquettes et ton mot-clé en retournant sur la piste.",
    ],
    express: { texte: "Une chose qui marche, une à ajuster, une intention.", secondes: 20 },
    guide: { type: "minuteur", secondes: 90 },
    sports: ["padel"],
    principe: "communication",
  },
  {
    id: "padel-apres-match-duo",
    titre: "Le debrief à deux",
    categorie: "apres-match",
    duree: 6,
    difficulte: "moyen",
    quand: ["apres"],
    objectif: "Faire un bilan constructif avec ton partenaire.",
    description: "Un échange court, centré sur ce que vous contrôlez, quel que soit le score.",
    etapes: [
      "Chacun dit une chose que l'autre a bien faite.",
      "Chacun dit un moment où vous avez bien rebondi ensemble.",
      "Choisissez une seule piste commune (communication, placement, tactique).",
      "Terminez par ce que vous voulez garder pour le prochain match.",
    ],
    guide: { type: "etapes" },
    sports: ["padel"],
    principe: "communication",
  },

  // ————————————————————————— VOLLEY-BALL —————————————————————————
  {
    id: "volley-reset-collectif",
    titre: "Le reset collectif",
    categorie: "communication",
    duree: 5,
    difficulte: "facile",
    quand: ["pendant", "hors-terrain"],
    objectif: "Casser une série adverse en vous regroupant.",
    description: "Un regroupement de quelques secondes, toujours le même, après chaque point perdu.",
    etapes: [
      "Après le point, regroupement au centre en deux secondes.",
      "Un contact (main, épaule) et un regard pour chacun.",
      "Le capitaine ou un joueur dit une phrase : « On repart. Réception haute. »",
      "Chacun retourne à sa place avec sa tâche en tête.",
      "À l'entraînement, faites-le après chaque point perdu pendant tout un set.",
    ],
    express: { texte: "Regroupement, un regard : « On repart. »", secondes: 5 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "communication",
  },
  {
    id: "volley-service-routine",
    titre: "Ma routine de service",
    categorie: "concentration",
    duree: 5,
    difficulte: "moyen",
    quand: ["pendant", "hors-terrain"],
    objectif: "Servir avec une intention claire plutôt que pour éviter la faute.",
    description: "Une routine fixe derrière la ligne : toujours la même, même sous pression.",
    etapes: [
      "Prends le ballon et fais-le rebondir deux fois, à ton rythme.",
      "Expire longuement.",
      "Regarde la zone que tu vises. Dis-la dans ta tête : « Zone 1. »",
      "Ton mot-clé, puis lancer et frappe.",
      "À l'entraînement, fais 20 services avec la routine complète, en annonçant ta zone.",
    ],
    express: { texte: "Deux rebonds, expire, regarde ta zone, frappe.", secondes: 8 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "routine-4-temps",
  },
  {
    id: "volley-reception-reset",
    titre: "Après une réception ratée",
    categorie: "erreurs",
    duree: 4,
    difficulte: "moyen",
    quand: ["pendant", "hors-terrain"],
    objectif: "Revenir prêt pour le service suivant, quelques secondes plus tard.",
    description: "L'action suivante arrive vite. Ce reset tient entre deux services.",
    etapes: [
      "Le fait, en un mot : « Trop loin », « Trop court ».",
      "Frotte tes paumes et expire longuement.",
      "Une consigne pour la suivante : « Plateau stable, balle haute au centre. »",
      "Fléchis les jambes et regarde le serveur adverse.",
    ],
    express: { texte: "Un mot. Paumes. Expire. « Plateau stable. »", secondes: 6 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "erreur-information",
  },
  {
    id: "volley-encouragements",
    titre: "Encourager après chaque action",
    categorie: "communication",
    duree: 5,
    difficulte: "facile",
    quand: ["pendant", "hors-terrain"],
    objectif: "Créer un climat d'équipe qui aide à rebondir.",
    description: "Des mots courts et positifs, même après une balle ratée. L'équipe repart plus vite.",
    etapes: [
      "Choisissez ensemble 3 phrases courtes : « Bien tenté », « Suivante », « Avec toi ».",
      "Après une action ratée d'un coéquipier, dis l'une d'elles, en le regardant.",
      "Après une action réussie, nomme ce qui était bien : « Belle réception ! »",
      "Appelle tes balles fort et tôt : « J'ai ! »",
    ],
    express: { texte: "Un regard et « Avec toi » à ton coéquipier.", secondes: 3 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "communication",
  },
  {
    id: "volley-entree-remplacant",
    titre: "Entrer en jeu à chaud",
    categorie: "avant-match",
    duree: 3,
    difficulte: "moyen",
    quand: ["pendant"],
    objectif: "Être prêt en quelques secondes quand le coach t'appelle.",
    description: "Une routine d'entrée express pour les remplaçants, à préparer depuis le banc.",
    etapes: [
      "Sur le banc, reste actif : suis le jeu, lis les rotations.",
      "Quand on t'appelle : trois sauts, une longue expiration.",
      "Demande ou rappelle-toi ta mission : service, bloc, réception ou défense.",
      "En entrant, tape dans la main de tes coéquipiers : « Je suis là. »",
    ],
    express: { texte: "Trois sauts, une expiration, ta mission.", secondes: 10 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "activation",
  },
  {
    id: "volley-role-poste",
    titre: "Mon intention de poste",
    categorie: "confiance",
    duree: 6,
    difficulte: "moyen",
    quand: ["hors-terrain", "avant"],
    objectif: "Avoir une intention et des mots-clés adaptés à ton poste.",
    description: "Passeur, libéro, attaquant, central : chacun a sa tâche principale. Tu la clarifies.",
    etapes: [
      "Écris ton poste et ta tâche principale en une phrase.",
      "Choisis 2 ou 3 mots-clés de poste (ex. libéro : « Appel », « Bas », « Stable »).",
      "Rappelle-toi un match où tu as bien tenu ce rôle. Qu'as-tu fait de bien ?",
      "Avant le match, dis-toi ton intention de poste.",
    ],
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "confiance-preuves",
  },
  {
    id: "volley-energie-sets",
    titre: "Gérer l'énergie sur plusieurs sets",
    categorie: "motivation",
    duree: 5,
    difficulte: "moyen",
    quand: ["pendant", "hors-terrain"],
    objectif: "Garder de l'énergie physique et mentale jusqu'au dernier set.",
    description: "Entre les sets, tu recharges plutôt que de ressasser le set précédent.",
    etapes: [
      "Entre deux sets : bois, expire longuement trois fois.",
      "Une chose que l'équipe fait bien, une seule chose à ajuster.",
      "Évalue ton énergie de 1 à 5. Trop bas : quelques sauts. Trop haut : expirations longues.",
      "Rappelle-toi ton intention de poste en revenant sur le terrain.",
    ],
    express: { texte: "Bois, expire trois fois, ton intention de poste.", secondes: 20 },
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "activation",
  },
  {
    id: "volley-bilan-equipe",
    titre: "Le bilan d'équipe",
    categorie: "apres-match",
    duree: 8,
    difficulte: "moyen",
    quand: ["apres"],
    objectif: "Apprendre ensemble du match, sans chercher de coupable.",
    description: "Un tour de table court et bienveillant, centré sur le collectif.",
    etapes: [
      "Chacun cite une action réussie d'un coéquipier.",
      "L'équipe identifie un moment où elle a bien cassé une série adverse.",
      "Choisissez une seule priorité collective pour le prochain entraînement.",
      "Terminez par un mot d'équipe.",
    ],
    guide: { type: "etapes" },
    sports: ["volley"],
    principe: "communication",
  },
];
